ITEM.name = "Storm Trooper Uniform"
ITEM.description = "A white plastoid composite worn over a black body glove."
ITEM.category = "Armor"
ITEM.model = "models/props_junk/cardboard_box001a.mdl"
ITEM.width = 1
ITEM.height = 1
ITEM.outfitCategory = "Empire"
ITEM.newSkin = 1
ITEM.replacements = "models/player/venator/anh2/anh_stormtrooper2.mdl"
